on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [esp8266-arduino-heap, esp8266-arduino-stack]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build ${{ matrix.example }}
        working-directory: exmples/${{ matrix.example }}/
        run: pio run
